### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Getnet12**
# Description

Merged the upstream changes to my repo

### CODE REVIEW

**Comment by kirubeltadesse** [comment]
I don't see any fill change with this PR

**Comment by Getnet12** [comment]
> I don't see any fill change with this PR

I only fetched the upstream to my forked repo. It was saying compare and pull request. Was I supposed to just leave it like that?

**Comment by kirubeltadesse** [comment]
For fetching from the upstream you don't need to open a PR (Pull Request). 

Pull Request:- is a way of saying "Hi have some change that needs to be merge with the main repository" 

Since we don't really have nothing to be merge in this case. I will close the PR. Great Job Keep it up 👍🏼 This is how we learn

**Comment by Getnet12** [comment]
> For fetching from the upstream you don't need to open a PR (Pull Request).
> 
> Pull Request:- is a way of saying "Hi have some change that needs to be merge with the main repository"
> 
> Since we don't really have nothing to be merge in this case. I will close the PR. Great Job Keep it up 👍🏼 This is how we learn

Got it, thanks.

**Pull request closed without merging**
